### ISSUE TITLE
Probleme de compilation

### ISSUE THREAD

**Issue by Wateir** [Vexcited/odm-2024#1]
Sa download pas les fichier quand on a pas internet

**Comment by Vexcited** [comment]
C'est normal, il faut obligatoirement Internet pour que le projet fonctionne (vu qu'[il y a un client mail derrière pour l'OTP notamment](<https://github.com/Vexcited/odm-2024/blob/main/src/server/mail.ts>) et [les fonts qui sont récupérés depuis Google Fonts par UnoCSS](<https://github.com/Vexcited/odm-2024/blob/main/uno.config.ts#L9-L13>))
